### ISSUE TITLE
OR error 

### ISSUE THREAD

**Issue by SuperKaa** [coffinxp/loxs#44]
i run the python file and i do option 2 for OR then i get an error when i select payloads/or.txt 
![image](https://github.com/user-attachments/assets/01b1dbf6-ae5a-437b-9fb2-1b2be589cfcb)
thanks

**Comment by CyberPro010** [comment]
reinstall tool and try again

-cyberpro010

**Comment by ghost** [comment]
Hello,

This issue is related to character encoding, because the tool is attempting to read payloads/or.txt with a default encoding that doesn’t support certain characters in the file.

For now, try using the default payload list we provide, which should work without issues. 

I’ll work on a fix to handle potential UTF-8 encoding errors in custom lists tomorow

hexsh1dow

**Comment by ghost** [comment]
Update: 

It looks like you are already using the default file You can try putting the or.txt file in the root of the tool | try updating the code and make sure you install all the requirements 

hexsh1dow

**Comment by SuperKaa** [comment]
hi, just reinstalled everything and ran the code but i still get the same error even after i put or.txt in the root, is there any fix to this?

**Comment by ghost** [comment]
Hello,

try to create a short list to see where the problem is, from my side everything works so try this and tell me

hexsh1dow

**Comment by SuperKaa** [comment]
so i deleted all special characters from or.txt and it doesnt give me that error but now it says this 
![image](https://github.com/user-attachments/assets/609e126d-d3a3-4c4f-b475-4de5bde03054)

**Comment by ghost** [comment]
Hey,

So yes, there is a problem, are you in a sandbox or something like that ?

hexsh1dow

**Comment by SuperKaa** [comment]
no i am using my main windows pc with no sandbox i am using cmd to run the file

**Comment by CyberPro010** [comment]
bro it is linux compatible

**Comment by CyberPro010** [comment]
your pc have issues not or.txt

**Comment by SuperKaa** [comment]
ohhhh ill try on linux

**Comment by SuperKaa** [comment]
how do i fix this then? 
![image](https://github.com/user-attachments/assets/e4380144-f943-4c61-b9c4-5c167d3975d2)

**Comment by ghost** [comment]
Hello, 

It seems that you have not installed the correct version of Chrome driver, you can directly find the correct one in the readme file. 


hexsh1dow

**Comment by 1hehaq** [comment]
> i run the python file and i do option 2 for OR then i get an error when i select payloads/or.txt ![image](https://private-user-images.githubusercontent.com/106885631/380256207-01b1dbf6-ae5a-437b-9fb2-1b2be589cfcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDYxODMsIm5iZiI6MTczMDA0NTg4MywicGF0aCI6Ii8xMDY4ODU2MzEvMzgwMjU2MjA3LTAxYjFkYmY2LWFlNWEtNDM3Yi05ZmIyLTFiMmJlNTg5Y2ZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNjE4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmFiMGJmYTBhYjg0YmUzMTU2NjNhYzUzMmI1OTY5M2ZjMzczNTRjNTlkODkwNDliOGE0ZDg4YmZmYjE5MzU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.69YChSd6qvJ3U9SAumlPzrO6Qp6o13PbgSXzvVPzcYM) thanks

**Hello**, 

We have patched the issue. Can you confirm that the issue has been fixed?

**Comment by 1hehaq** [comment]
> how do i fix this then? ![image](https://private-user-images.githubusercontent.com/106885631/380503371-e4380144-f943-4c61-b9c4-5c167d3975d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNDYxODMsIm5iZiI6MTczMDA0NTg4MywicGF0aCI6Ii8xMDY4ODU2MzEvMzgwNTAzMzcxLWU0MzgwMTQ0LWY5NDMtNGM2MS1iOWM0LTVjMTY3ZDM5NzVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxNjE4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDJjNWUwMmI1ZDQ1NTY1YTI4ZGI2MDYxMGI2ZDllYjc1MmFiY2Y5ODU4Y2Q0OTVlNjE4NDBiYTRjYTAxYjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PMLzzDZvY_0T949PfJMvNgVCMcZfaAJ52sios6wbEhQ)


Make sure all requirements installed as detailed in the README.md, remove existing chrome from the $PATH and install the README.md mentioned version of chrome

Let us know if you continue to experience the same issues

**Regards**

**Comment by 1hehaq** [comment]
> bro it is linux compatible

**LOXS** is a cross platform compatible tool, so you can run in any OSes

Even you can try it in termux _(Make sure all requirements are installed)_

**Comment by SuperKaa** [comment]
hi, so i want to use the tool in windows, i have install all requirements and everything is up to date i have even re downloaded just now the loxs tool but i still get this error 
![image](https://github.com/user-attachments/assets/a78c7d1a-257b-49b2-90c8-1e17d5dfdd73)

**Comment by 1hehaq** [comment]
> hi, so i want to use the tool in windows, i have install all requirements and everything is up to date i have even re downloaded just now the loxs tool but i still get this error 
> ![image](https://github.com/user-attachments/assets/a78c7d1a-257b-49b2-90c8-1e17d5dfdd73)
> 
> 

Hello,

We will try to resolve this issues, let you know after a fix

Best regards,
Haq

**Comment by CyberPro010** [comment]
> > bro it is linux compatible
> 
> **LOXS** is a cross platform compatible tool, so you can run in any OSes
> 
> Even you can try it in termux _(Make sure all requirements are installed)_

bro it works best on linux

**Comment by 1hehaq** [comment]
> > > bro it is linux compatible
> > 
> > **LOXS** is a cross platform compatible tool, so you can run in any OSes
> > 
> > Even you can try it in termux _(Make sure all requirements are installed)_
> 
> bro it works best on linux 

Hello,

You can run it on Linux as well, but that doesn’t mean loxs isn’t compatible with other operating systems.

Regards
